server:server.c
	cc -g -w -o server server.c
client:client.c
	cc -g -w -o client client.c
proxy:proxy.c
	cc -g -w -o proxy proxy.c
poll_server:test_poll.c
	cc -g -w -o poll_server test_poll.c
test_proxy:test_proxy.c
	cc -g -w -o test_proxy test_proxy.c
